[ARC-1926]login fargment added
giorgiqemoklidze/TaskPlanner pull request #1
Opened 2021-11-24 12:00 UTC by giorgiqemoklidze

https://spaceneobank.atlassian.net/browse/ARC-1926

2021-11-24 16:25 UTC, GiorgiMamagulashvili16 approved these changes

2021-11-27 06:53 UTC, GiorgiMamagulashvili16 approved these changes

2021-12-01 07:40 UTC, AnaRusadze requested changes

2021-12-01 07:40 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/model/User.kt
> +data class User(val email: String, val password: String)
იუზერ კლასს თავისი აიდიც უნდა ჰქონდეს, იუზერნეიმიც, სურათიც, პროექტების სიაც, პროფესიაც

2021-12-01 07:40 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/repository/loginrepository/LogInRepositoryImplement.kt
> +typealias isUserLoggedIn = (Response<String>) -> Unit
ბულიანი არ უნდა იყოს?

2021-12-01 07:40 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/repository/loginrepository/LogInRepositoryImplement.kt
> +typealias isUserLoggedIn = (Response<String>) -> Unit
ისეთი სახელი აქვს, ბულიანს ელოდები თითქოს, userLoginMessage დაარქვი მაშინ

2021-12-01 07:40 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/ui/login/LogInViewModel.kt
> +            else -> logIn(User(email,password))
ჩემი რჩევაა იმეილის და პაროლის ვალიდაცია ცალ-ცალკე ფუნქციებში გაიტანო აქვე, უფრო წაკითხვადი იქნება

2021-12-01 10:04 UTC, giorgiqemoklidze commented on app/src/main/java/com/example/taskplanner/model/User.kt
> +data class User(val email: String, val password: String)
done

2021-12-01 10:04 UTC, giorgiqemoklidze commented on app/src/main/java/com/example/taskplanner/repository/loginrepository/LogInRepositoryImplement.kt
> +typealias isUserLoggedIn = (Response<String>) -> Unit
done

2021-12-01 10:04 UTC, giorgiqemoklidze commented on app/src/main/java/com/example/taskplanner/ui/login/LogInViewModel.kt
> +            else -> logIn(User(email,password))
done

2021-12-01 10:44 UTC, AnaRusadze approved these changes

2021-12-01 10:44 UTC, merged