[ARC-1927]Feature/add home page arc 1927
giorgiqemoklidze/TaskPlanner pull request #3
Opened 2021-12-13 09:53 UTC by giorgiqemoklidze

https://spaceneobank.atlassian.net/browse/ARC-1927

2021-12-15 09:13 UTC, AnaRusadze requested changes

2021-12-15 09:13 UTC, AnaRusadze commented on app/src/main/res/layout/user_projects_status_layout.xml
> +         />
ctrl alt l

2021-12-15 09:13 UTC, AnaRusadze commented on app/src/main/res/values/strings.xml
> +    <string name="enter_password_error">Pls enter password</string>
please :D

2021-12-17 21:06 UTC, giorgiqemoklidze commented on app/src/main/java/com/example/taskplanner/model/SubTask.kt
> +    val taskStatus: String? = "TODO",
done

2021-12-17 21:07 UTC, giorgiqemoklidze commented on app/src/main/java/com/example/taskplanner/ui/home_page/HomeFragment.kt
> +        //Navigation to project details fragment
ა აქ კომენტარი იმიტომაქ რო სადაც ნავიგაცია უნდა გაკეთდეს ჯერ ის არამაქ დაიმპლემენტირებული და გასაგები რო იყოს მანდ რაუნდა მოხდეს , წავშალო მაინც ?

2021-12-17 21:08 UTC, giorgiqemoklidze commented on app/src/main/res/layout/user_projects_status_layout.xml
> +         />
done

2021-12-17 21:10 UTC, giorgiqemoklidze commented on app/src/main/res/values/strings.xml
> +    <string name="enter_password_error">Pls enter password</string>
done :D :D :D

2021-12-20 09:16 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/ui/home_page/HomeFragment.kt
> +        //Navigation to project details fragment
არაა იყოს მაშინ

2021-12-20 09:16 UTC, AnaRusadze commented on app/src/main/res/layout/project_recycler_item.xml
> +        android:textColor="#839BB1"
ფერების რესურსში გაიტანე

2021-12-20 09:20 UTC, GiorgiMamagulashvili16 approved these changes

2021-12-20 09:21 UTC, giorgiqemoklidze commented on app/src/main/res/layout/project_recycler_item.xml
> +        android:textColor="#839BB1"
done

2021-12-20 09:23 UTC, AnaRusadze approved these changes

2021-12-20 09:23 UTC, merged