[ARC-1966]create project fragment added
giorgiqemoklidze/TaskPlanner pull request #4
Opened 2021-12-20 10:29 UTC by giorgiqemoklidze

https://spaceneobank.atlassian.net/browse/ARC-1966

2021-12-21 07:47 UTC, GiorgiMamagulashvili16 approved these changes

2021-12-21 09:57 UTC, AnaRusadze requested changes

2021-12-21 09:57 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/repository/user_projects_repository/UserProjectsRepositoryImpl.kt
> +        private const val STATUS = "status"
ეს ცვლადები რად გინდა, პირდაპირ ენამის სტატუსიდან რო ამოიღო?

2021-12-21 09:57 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/ui/custom_view/CustomDataPicker.kt
> +    fun initDataPicker(textView: TextView) {
custom view-მ არ უნდა იცოდეს კონკრეტული ტექსტვიუს შესახებ. ფუნქცია უნდა აბრუნებდეს სტრინგს ან მეორე ვარიანტი გაქვს, ცალკე ცვლადი უნდა იყოს, რომელიც public იქნება, მას მიანიჭებ კალენდრის ტექსტის მნიშვნელობას და ამ ცვლადს მიწვდები ფრაგმენტში. მოკლედ, ტექსტვიუს set Text უნდა მოხდეს ფრაგმენტში

2021-12-21 09:57 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/ui/custom_view/CustomDataPicker.kt
> +        button = binding.saveDateButton
ბაინდინგის ცვლადი გლობალური უნდა გახადო

2021-12-21 09:57 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/ui/custom_view/CustomDataPicker.kt
> +    private var button: AppCompatButton
ბაინდინგის ცვლადს რომ გლობალურს გახდი, ესენი აღარ დაგჭირდება

2021-12-21 09:57 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/ui/custom_view/CustomDataPicker.kt
> +                    this.visibility = View.GONE
ქემო, ამ ყვცელაფერის შენი ხელით დაწერა შეცდომაა, https://stackoverflow.com/questions/14851285/how-to-get-datepicker-value-in-date-format დეითის დაკონვერტირება შეგიძლია, ჯერ ასე სცადე და თუ რამეა მერე მომწერე

2021-12-21 09:57 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/ui/custom_view/CustomDataPicker.kt
> +                    this.visibility = View.GONE
ვიზიბილითის gone ყველა შემთხვევაში ხდება? მაშინ იფის გარეთ გაიტანე

2021-12-21 09:57 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/ui/home_page/adapters/RecyclerAdapter.kt
> +        }else if(item is SubTask){
კაი იქნება რომ elseში throw exception დააბრუნო რო ვიუ ტაიპი არასწორია

2021-12-21 09:57 UTC, AnaRusadze commented on app/src/main/java/com/example/taskplanner/utils/extensions/StringExtensions.kt
>  }
ესენი რას შვრება ზუსტად რო მითხრა?

2021-12-21 14:47 UTC, giorgiqemoklidze commented on app/src/main/java/com/example/taskplanner/repository/user_projects_repository/UserProjectsRepositoryImpl.kt
> +        private const val STATUS = "status"
აა ესენი არის path ebi

2021-12-21 14:47 UTC, giorgiqemoklidze commented on app/src/main/java/com/example/taskplanner/ui/custom_view/CustomDataPicker.kt
> +    fun initDataPicker(textView: TextView) {
done

2021-12-21 14:47 UTC, giorgiqemoklidze commented on app/src/main/java/com/example/taskplanner/ui/custom_view/CustomDataPicker.kt
> +        button = binding.saveDateButton
done

2021-12-21 14:47 UTC, giorgiqemoklidze commented on app/src/main/java/com/example/taskplanner/ui/custom_view/CustomDataPicker.kt
> +    private var button: AppCompatButton
done

2021-12-21 14:47 UTC, giorgiqemoklidze commented on app/src/main/java/com/example/taskplanner/ui/custom_view/CustomDataPicker.kt
> +                    this.visibility = View.GONE
done აუ მადლობა რამხელა ხლამი კოდი მოვიშორე <3 <3

2021-12-21 14:47 UTC, giorgiqemoklidze commented on app/src/main/java/com/example/taskplanner/ui/custom_view/CustomDataPicker.kt
> +                    this.visibility = View.GONE
საერთოდ მომშორდა ეს ხლამი :დ

2021-12-21 14:47 UTC, giorgiqemoklidze commented on app/src/main/java/com/example/taskplanner/ui/home_page/adapters/RecyclerAdapter.kt
> +        }else if(item is SubTask){
done  მარა რამდენად სწორად ვქენი არვიცი :დ

2021-12-21 14:48 UTC, giorgiqemoklidze commented on app/src/main/java/com/example/taskplanner/utils/extensions/StringExtensions.kt
>  }
აა ფაიერბეისზე თარიღს ვინახავ სტრინგად და შედარებას აკეთებს ჯერ ყველა სიმბოლოს რომელიც / ესაა ცვლის ცარიელად ანუ შლის და  მერე ინტად გადაყავს და ადარებს რომელი უფრო  დიდია მარა ახლა ეს შევცვალე რა და / ამეების მაგივრად - ამას წაშლის და .reverse დაემატება რო უკნიდან წაიკითხოს :D :D

2021-12-28 08:35 UTC, giorgiqemoklidze commented on app/src/main/java/com/example/taskplanner/utils/extensions/StringExtensions.kt
>  }
ესენი ამოვიღე საერთოდ აღარ მაქ

2022-01-11 15:01 UTC, merged